name: Docker images build and push

on:
  workflow_dispatch
  push:
    branches: [ "main" ]
    # paths-ignore:   # 排除文件
    #   - 'README.md'
    # paths:    # 包含文件
    # - 'actions-time.txt'
    #   - 'Dockerfile'
    #   - 'src/**'
  # schedule:
    # - cron: "0 0 12 * *"   # 每天中午12点

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ilkeiii
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          # file: Dockerfile.aarch64
          push: true # push to docker hub
          tags: |
              ilkeiii/m-py-sub:latest
          platforms: linux/amd64 #,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x
